hosts:
  - name: 'server'
    mac: 'AA:BB:CC:DD:EE:FF'
    address: '192.168.1.1'
nut_server:
  host: 'localhost'
  port: 3493
  username: 'username'
  password: 'password'
ups_name: 'myUPS'
wake_on:
  batt_level_gte: 30
  runtime_gte: 360
  ups_status_str: 'OL'
