hosts:
  - name: 'server'
    mac: 'AA:BB:CC:DD:EE:FF'
    address: '192.168.1.1'
nut_server:
  host: 'localhost'
  port: 3493
  username: 'username'
  password: 'password'
ups_name: 'myUPS'
wake_on:
  charge: 30
  runtime: 360
  status: 'OL'
  delay: 60
